//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalOperationPermission
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string ScreenOperationId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
        public string Note { get; set; }
    
        public virtual ScreenOperation ScreenOperation { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
