//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityInformation
    {
        public long ApplicationId { get; set; }
        public byte ApplicationIdLength { get; set; }
        public long ModuleId { get; set; }
        public byte ModuleIdLength { get; set; }
        public long ScreenId { get; set; }
        public byte ScreenIdLength { get; set; }
        public long MenuId { get; set; }
        public byte MenuIdLength { get; set; }
        public long UserTypeId { get; set; }
        public byte UserTypeIdLength { get; set; }
        public long RoleId { get; set; }
        public byte RoleIdLength { get; set; }
        public long PersonId { get; set; }
        public byte PersonIdLength { get; set; }
        public long ScreenOperationId { get; set; }
        public byte ScreenOperationIdLength { get; set; }
        public long ApplicationPolicyId { get; set; }
        public byte ApplicationPolicyIdLength { get; set; }
    }
}
