//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAudit
    {
        public long Id { get; set; }
        public string RoleId { get; set; }
        public long ScreenOperationId { get; set; }
        public bool HaveAccess { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
        public string Note { get; set; }
        public string DataStatusFlag { get; set; }
    }
}
